export const HOLD_CARD = 'HOLD_CARD';
export const BUY_CARD = 'BUY_CARD';
export const TOGGLE_TOKEN_SELECTION = 'TOGGLE_TOKEN_SELECTION';
export const PICK_SELECTED = 'PICK_SELECTED';
export const PICK_DOUBLE = 'PICK_DOUBLE';
export const SWITCH_PLAYER = 'SWITCH_PLAYER';
export const NOBLE_COMING = 'NOBLE_COMING';

export const FETCH_GAMES_BEGIN = 'FETCH_GAMES_BEGIN';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
